# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

variables:
  - group: deploy-vars

stages:
  - stage: Build
    jobs:
      - template: templates/build.yml
        parameters:
          imageName: springboot-builder

  - stage: SAST
    dependsOn: Build
    jobs:
      - template: templates/sast.yml

  - stage: Release
    dependsOn: SAST
    jobs:
      - template: templates/release.yml

  - stage: Deploy
    dependsOn: Release
    jobs:
      - template: templates/deploy.yml

