# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

variables:
  - group: github-packages-auth

stages:
  - stage: Build
    jobs:
      - template: templates/build.yml
        parameters:
          dockerImage: gradle:8.5.0-jdk17

  - stage: SAST
    dependsOn: Build
    jobs:
      - template: templates/sast.yml
        parameters:
          sonarProjectKey: 'springboot_ci_cd'
          sonarOrganization: 'roni-cadena81'
          sonarToken: $(SONAR_TOKEN)  # Asegúrate que esta variable esté en tu Variable Group

  - stage: Release
    dependsOn: SAST
    jobs:
      - template: templates/release.yml
        parameters:
          githubUser: Ronnie811
          githubRepo: springboot_ci_cd
          githubOrg: roni-cadena81
          projectName: spring-app
          jarFile: build/libs/spring-app-0.0.1-SNAPSHOT.jar

#  - stage: Deploy
#    dependsOn: Release
#    jobs:
#      - template: templates/deploy.yml
#        parameters:
#          jarPath: 'build/libs/spring-app-0.0.1-SNAPSHOT.jar'
#          remoteHost: $(REMOTE_HOST)
#          remoteUser: $(REMOTE_USER)
#          remoteDeployPath: $(REMOTE_DEPLOY_PATH)
#          serviceName: $(SERVICE_NAME)

