parameters:
  - name: dockerImage
    type: string

jobs:
  - job: Build
    displayName: 'Build Java Project'
    pool:
      vmImage: 'ubuntu-latest'

    container: 
      image: ${{ parameters.dockerImage }}

    steps:
      - checkout: self

      - script: |
          echo "Verificando versión de Gradle"
          gradle --version
        displayName: 'Gradle Version Check'

      - script: |
          echo "Limpiando y construyendo el proyecto con Gradle"
          gradle clean build
        displayName: 'Build Java Project with Gradle'

      - script: |
          echo "Verificando directorio de salida"
          find . -type d -name classes || echo "No se encontraron directorios 'classes'"
        displayName: 'Verificar binarios .class generados'

