parameters:
  - name: dockerImage
    type: string

jobs:
  - job: Build
    displayName: 'Build Java Project'
    pool:
      vmImage: 'ubuntu-latest'

    container: 
      image: ${{ parameters.dockerImage }}

    steps:
      - checkout: self

      - script: |
          echo "Verificando versión de Gradle"
          gradle --version
        displayName: 'Gradle Version Check'

      - script: |
          echo "Limpiando y construyendo el proyecto con Gradle"
          gradle clean build
        displayName: 'Build Java Project with Gradle'

      - script: |
          echo "Verificando directorio de salida"
          find . -type d -name classes || echo "No se encontraron directorios 'classes'"
        displayName: 'Verificar binarios .class generados'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: 'build/libs'
          artifactName: 'jar-artifacts'
          publishLocation: 'Container'
        displayName: 'Publish JAR Artifacts'
        
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)'
          artifactName: 'build-output'
          publishLocation: 'Container'
        displayName: 'Publish Build Artifacts'