parameters:
  - name: dockerImage
    type: string
    default: 'springboot-builder'

  - name: workingDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)'

jobs:
  - job: BuildJob
    displayName: Build with Docker
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          echo "Building application with Docker image: ${{ parameters.dockerImage }}"
          docker run --rm \
            -v ${{ parameters.workingDirectory }}:/app \
            -w /app \
            ${{ parameters.dockerImage }} \
            ./gradlew clean build
        displayName: 'Build Spring Boot App with Docker'

