parameters:
  - name: jarPath
    type: string
    default: 'build/libs/spring-app-0.0.1-SNAPSHOT.jar'
  - name: remoteHost
    type: string
  - name: remoteUser
    type: string
  - name: remoteDeployPath
    type: string
  - name: serviceName
    type: string

jobs:
  - job: DeployJob
    displayName: Deploy JAR to Remote Server
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: 'remote-ssh-service'  # Definido en Service Connections
          sourceFolder: '$(System.DefaultWorkingDirectory)'
          contents: '${{ parameters.jarPath }}'
          targetFolder: '${{ parameters.remoteDeployPath }}/backup'

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            echo "[INFO] Connecting via SSH to deploy JAR"

            ssh ${{ parameters.remoteUser }}@${{ parameters.remoteHost }} <<EOF
              echo "[INFO] Creating backup of existing jar (if exists)"
              mkdir -p ${{ parameters.remoteDeployPath }}/backup
              cp ${{ parameters.remoteDeployPath }}/app.jar ${{ parameters.remoteDeployPath }}/backup/app-$(date +%s).jar || true

              echo "[INFO] Replacing jar"
              cp ${{ parameters.remoteDeployPath }}/backup/$(basename ${{ parameters.jarPath }}) ${{ parameters.remoteDeployPath }}/app.jar

              echo "[INFO] Restarting service"
              sudo systemctl restart ${{ parameters.serviceName }}

              echo "[INFO] Health check"
              curl -f http://localhost:8080/actuator/health || exit 1
            EOF
        displayName: Deploy and Restart

