parameters:
  - name: projectName
    type: string
    default: 'spring-app'
  - name: jarFile
    type: string
    default: 'build/libs/spring-app-0.0.1-SNAPSHOT.jar'
  - name: githubUser
    type: string
    default: 'Ronnie811'
  - name: githubRepo
    type: string
    default: 'springboot_ci_cd'
  - name: githubOrg
    type: string
    default: 'roni-cadena81'

jobs:
  - job: release
    displayName: Publish JAR to GitHub Packages
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self

      - task: Bash@3
        name: PublishJar
        inputs:
          targetType: 'inline'
          script: |
            echo "Publishing to GitHub Packages..."

            echo "[INFO] Configuring Maven settings"
            mkdir -p ~/.m2
            echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"' > ~/.m2/settings.xml
            echo '         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"' >> ~/.m2/settings.xml
            echo '         xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">' >> ~/.m2/settings.xml
            echo '  <servers>' >> ~/.m2/settings.xml
            echo '    <server>' >> ~/.m2/settings.xml
            echo '      <id>github</id>' >> ~/.m2/settings.xml
            echo "      <username>${{ parameters.githubUser }}</username>" >> ~/.m2/settings.xml
            echo "
